name: Stopthehush
favicon: null
layout_spectrum: 0.50251
typography_spectrum: 0.6112
title: 'HUSH: Breaking the Silence of Infertility'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7ffec'
    - '#aa3494'
    - '#000000'
    - '#ff0000'
    - '#00ffff'
  brandStrength: 0.8807112162467092
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
